#!/usr/bin/perl
use strict;
use warnings;

my $script = "/opt/qtbigtext/qtbigtext.py";

sub python();
sub killBigText();
sub isRunning();
sub dbusCall($);
sub setBigText($);

sub main(@){
  if(@_ == 1 and $_[0] eq "-k"){
    killBigText();
  }elsif(@_ == 1 and -e $_[0]){
    my $file = shift;
    open FH, "< $file";
    my $contents = join '', <FH>;
    close FH;
    setBigText $contents;
  }else{
    setBigText "@_";
  }
}

sub python(){
  my $python = '';
  $python = `which python3   2>/dev/null` if $python !~ /python/;
  $python = `which python2.7 2>/dev/null` if $python !~ /python/;
  $python = `which python2.6 2>/dev/null` if $python !~ /python/;
  $python = `which python2   2>/dev/null` if $python !~ /python/;
  $python = `which python    2>/dev/null` if $python !~ /python/;
  chomp $python;
  return $python;
}

sub killBigText(){
  system "pkill", "-f", $script;
}

sub isRunning(){
  my $python = python();
  system "pkill", "-0", "-f", "-x", "$python $script";
  return $? == 0;
}

sub dbusCall($){
  my $str = shift;
  my $dest = "org.teleshoes.qtbigtext";
  my $path = "/";
  my $method = "setText";
  system "dbus-send", "--session", "--print-reply", "--type=method_call",
    "--dest=$dest",
    $path,
    "$dest.$method",
    "string:$str";
  return $? == 0;
}

sub setBigText($){
  my $str = shift;

  my $dbusOk = 0;
  if(isRunning()){
    $dbusOk = dbusCall $str;
  }

  if(not $dbusOk){
    killBigText();
    my $python = python;
    if(not fork){
      close STDOUT;
      close STDERR;
      open FH, "| $python $script";
      print FH $str;
      close FH;
    }
  }
}

&main(@ARGV);
